export function normalizeIndustryKey(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/[–—]/g, '-')
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
}

export const INDUSTRY_UNIVERSE = [
  { name: 'Business Equipment & Supplies', proxySymbol: '', aliases: [] },
  { name: 'Health Information Services', proxySymbol: '', aliases: [] },
  { name: 'Software - Application', proxySymbol: 'IGV', aliases: ['Software—Application'] },
  { name: 'Consumer Electronics', proxySymbol: '', aliases: [] },
  { name: 'Computer Hardware', proxySymbol: 'HARD', aliases: [] },
  { name: 'Solar', proxySymbol: 'TAN', aliases: [] },
  { name: 'Advertising Agencies', proxySymbol: '', aliases: [] },
  { name: 'Software - Infrastructure', proxySymbol: 'IGV', aliases: ['Software—Infrastructure'] },
  { name: 'Engineering & Construction', proxySymbol: '', aliases: [] },
  { name: 'Electrical Equipment & Parts', proxySymbol: '', aliases: [] },
  { name: 'Packaging & Containers', proxySymbol: '', aliases: [] },
  { name: 'Airlines', proxySymbol: 'JETS', aliases: [] },
  { name: 'Auto Manufacturers', proxySymbol: 'CARZ', aliases: [] },
  { name: 'Internet Retail', proxySymbol: 'ONLN', aliases: [] },
  { name: 'Communication Equipment', proxySymbol: '', aliases: [] },
  { name: 'REIT - Office', proxySymbol: '', aliases: [] },
  { name: 'Tobacco', proxySymbol: '', aliases: [] },
  { name: 'Mortgage Finance', proxySymbol: 'MORT', aliases: [] },
  { name: 'Silver', proxySymbol: 'SLV', aliases: [] },
  { name: 'Publishing', proxySymbol: '', aliases: [] },
  { name: 'Pharmaceutical Retailers', proxySymbol: '', aliases: [] },
  { name: 'Shell Companies', proxySymbol: '', aliases: [] },
  { name: 'Travel Services', proxySymbol: '', aliases: [] },
  { name: 'Semiconductors', proxySymbol: 'SOXX', aliases: [] },
  { name: 'REIT - Hotel & Motel', proxySymbol: '', aliases: [] },
  { name: 'Apparel Manufacturing', proxySymbol: '', aliases: [] },
  { name: 'Medical Care Facilities', proxySymbol: '', aliases: [] },
  { name: 'Specialty Chemicals', proxySymbol: '', aliases: [] },
  { name: 'Textile Manufacturing', proxySymbol: '', aliases: [] },
  { name: 'Household & Personal Products', proxySymbol: '', aliases: [] },
  { name: 'Department Stores', proxySymbol: '', aliases: [] },
  { name: 'Asset Management', proxySymbol: 'IAI', aliases: [] },
  { name: 'Information Technology Services', proxySymbol: 'IGV', aliases: [] },
  { name: 'Drug Manufacturers - Specialty & Generic', proxySymbol: '', aliases: ['Drug Manufacturers—Specialty & Generic'] },
  { name: 'REIT - Mortgage', proxySymbol: 'REM', aliases: [] },
  { name: 'Telecom Services', proxySymbol: 'IYZ', aliases: [] },
  { name: 'Chemicals', proxySymbol: 'XLB', aliases: [] },
  { name: 'Internet Content & Information', proxySymbol: '', aliases: [] },
  { name: 'Scientific & Technical Instruments', proxySymbol: '', aliases: [] },
  { name: 'Steel', proxySymbol: 'SLX', aliases: [] },
  { name: 'Drug Manufacturers - General', proxySymbol: '', aliases: ['Drug Manufacturers—General'] },
  { name: 'REIT - Healthcare Facilities', proxySymbol: '', aliases: [] },
  { name: 'Insurance - Diversified', proxySymbol: 'IAK', aliases: [] },
  { name: 'REIT - Specialty', proxySymbol: '', aliases: [] },
  { name: 'Apparel Retail', proxySymbol: 'XRT', aliases: [] },
  { name: 'Leisure', proxySymbol: '', aliases: [] },
  { name: 'Security & Protection Services', proxySymbol: '', aliases: [] },
  { name: 'Specialty Retail', proxySymbol: 'XRT', aliases: [] },
  { name: 'Financial Data & Stock Exchanges', proxySymbol: 'IAI', aliases: [] },
  { name: 'Capital Markets', proxySymbol: 'IAI', aliases: [] },
  { name: 'Other Precious Metals & Mining', proxySymbol: '', aliases: [] },
  { name: 'Medical Distribution', proxySymbol: '', aliases: [] },
  { name: 'Other Industrial Metals & Mining', proxySymbol: 'XME', aliases: [] },
  { name: 'Utilities - Renewable', proxySymbol: 'ICLN', aliases: [] },
  { name: 'Metal Fabrication', proxySymbol: 'XME', aliases: [] },
  { name: 'Insurance - Life', proxySymbol: 'IAK', aliases: [] },
  { name: 'REIT - Residential', proxySymbol: 'REZ', aliases: [] },
  { name: 'Discount Stores', proxySymbol: 'XRT', aliases: [] },
  { name: 'Utilities - Regulated Gas', proxySymbol: 'XLU', aliases: [] },
  { name: 'Marine Shipping', proxySymbol: 'BOAT', aliases: [] },
  { name: 'Footwear & Accessories', proxySymbol: '', aliases: [] },
  { name: 'Medical Instruments & Supplies', proxySymbol: 'IHI', aliases: [] },
  { name: 'REIT - Industrial', proxySymbol: 'INDS', aliases: [] },
  { name: 'Beverages - Brewers', proxySymbol: 'TAPX', aliases: [] },
  { name: 'Beverages - Non-Alcoholic', proxySymbol: '', aliases: [] },
  { name: 'Grocery Stores', proxySymbol: '', aliases: [] },
  { name: 'REIT - Retail', proxySymbol: 'RTL', aliases: [] },
  { name: 'Banks - Diversified', proxySymbol: 'KBE', aliases: [] },
  { name: 'Utilities - Diversified', proxySymbol: 'XLU', aliases: [] },
  { name: 'Real Estate Services', proxySymbol: 'IYR', aliases: [] },
  { name: 'Tools & Accessories', proxySymbol: '', aliases: [] },
  { name: 'Farm Products', proxySymbol: 'MOO', aliases: [] },
  { name: 'Confectioners', proxySymbol: '', aliases: [] },
  { name: 'Insurance Brokers', proxySymbol: 'IAK', aliases: [] },
  { name: 'Oil & Gas Drilling', proxySymbol: 'XOP', aliases: [] },
  { name: 'Education & Training Services', proxySymbol: '', aliases: [] },
  { name: 'Insurance - Property & Casualty', proxySymbol: 'KIE', aliases: [] },
  { name: 'Oil & Gas Equipment & Services', proxySymbol: 'IEZ', aliases: [] },
  { name: 'Pollution & Treatment Controls', proxySymbol: '', aliases: [] },
  { name: 'Utilities - Regulated Electric', proxySymbol: 'XLU', aliases: [] },
  { name: 'Furnishings, Fixtures & Appliances', proxySymbol: 'XHB', aliases: [] },
  { name: 'Credit Services', proxySymbol: '', aliases: [] },
  { name: 'Entertainment', proxySymbol: '', aliases: [] },
  { name: 'Aluminum', proxySymbol: 'JJU', aliases: [] },
  { name: 'Semiconductor Equipment & Materials', proxySymbol: 'XSD', aliases: [] },
  { name: 'Electronics & Computer Distribution', proxySymbol: '', aliases: [] },
  { name: 'Food Distribution', proxySymbol: '', aliases: [] },
  { name: 'Agricultural Inputs', proxySymbol: 'MOO', aliases: [] },
  { name: 'Recreational Vehicles', proxySymbol: '', aliases: [] },
  { name: 'Banks - Regional', proxySymbol: 'KRE', aliases: [] },
  { name: 'Consulting Services', proxySymbol: '', aliases: [] },
  { name: 'Airports & Air Services', proxySymbol: 'JETS', aliases: [] },
  { name: 'Railroads', proxySymbol: 'IYT', aliases: [] },
  { name: 'Broadcasting', proxySymbol: '', aliases: [] },
  { name: 'Building Products & Equipment', proxySymbol: 'ITB', aliases: [] },
  { name: 'Rental & Leasing Services', proxySymbol: '', aliases: [] },
  { name: 'Farm & Heavy Construction Machinery', proxySymbol: '', aliases: [] },
  { name: 'Industrial Distribution', proxySymbol: '', aliases: [] },
  { name: 'Real Estate - Development', proxySymbol: 'IYR', aliases: [] },
  { name: 'Diagnostics & Research', proxySymbol: '', aliases: [] },
  { name: 'Utilities - Regulated Water', proxySymbol: 'CGW', aliases: [] },
  { name: 'Copper', proxySymbol: 'COPX', aliases: [] },
  { name: 'Specialty Business Services', proxySymbol: '', aliases: [] },
  { name: 'Beverages - Wineries & Distilleries', proxySymbol: '', aliases: [] },
  { name: 'Healthcare Plans', proxySymbol: 'IHF', aliases: [] },
  { name: 'Biotechnology', proxySymbol: 'XBI', aliases: [] },
  { name: 'Aerospace & Defense', proxySymbol: 'ITA', aliases: [] },
  { name: 'Packaged Foods', proxySymbol: '', aliases: [] },
  { name: 'Oil & Gas Midstream', proxySymbol: 'AMLP', aliases: [] },
  { name: 'Oil & Gas Refining & Marketing', proxySymbol: 'CRAK', aliases: [] },
  { name: 'Personal Services', proxySymbol: '', aliases: [] },
  { name: 'Paper & Paper Products', proxySymbol: '', aliases: [] },
  { name: 'Oil & Gas Integrated', proxySymbol: 'XLE', aliases: [] },
  { name: 'Resorts & Casinos', proxySymbol: 'BJK', aliases: [] },
  { name: 'Building Materials', proxySymbol: 'ITB', aliases: [] },
  { name: 'Gambling', proxySymbol: 'BJK', aliases: [] },
  { name: 'Electronic Components', proxySymbol: 'XSD', aliases: [] },
  { name: 'REIT - Diversified', proxySymbol: 'VNQ', aliases: [] },
  { name: 'Waste Management', proxySymbol: '', aliases: [] },
  { name: 'Conglomerates', proxySymbol: '', aliases: [] },
  { name: 'Restaurants', proxySymbol: '', aliases: [] },
  { name: 'Lumber & Wood Production', proxySymbol: 'WOOD', aliases: [] },
  { name: 'Oil & Gas E&P', proxySymbol: 'XOP', aliases: [] },
  { name: 'Thermal Coal', proxySymbol: '', aliases: [] },
  { name: 'Utilities - Independent Power Producers', proxySymbol: 'ICLN', aliases: [] },
  { name: 'Gold', proxySymbol: 'GLD', aliases: [] },
  { name: 'Luxury Goods', proxySymbol: '', aliases: [] },
  { name: 'Lodging', proxySymbol: 'PEJ', aliases: [] },
  { name: 'Medical Devices', proxySymbol: 'IHI', aliases: [] },
  { name: 'Insurance - Reinsurance', proxySymbol: 'IAK', aliases: [] },
  { name: 'Integrated Freight & Logistics', proxySymbol: 'IYT', aliases: [] },
  { name: 'Uranium', proxySymbol: 'URA', aliases: [] },
  { name: 'Home Improvement Retail', proxySymbol: 'XHB', aliases: [] },
  { name: 'Specialty Industrial Machinery', proxySymbol: '', aliases: [] },
  { name: 'Residential Construction', proxySymbol: 'ITB', aliases: [] },
  { name: 'Insurance - Specialty', proxySymbol: 'KIE', aliases: [] },
  { name: 'Auto & Truck Dealerships', proxySymbol: 'CARZ', aliases: [] },
  { name: 'Auto Parts', proxySymbol: 'CARZ', aliases: [] },
  { name: 'Real Estate - Diversified', proxySymbol: 'IYR', aliases: [] },
  { name: 'Trucking', proxySymbol: 'IYT', aliases: [] },
  { name: 'Staffing & Employment Services', proxySymbol: '', aliases: [] },
  { name: 'Coking Coal', proxySymbol: '', aliases: [] },
  { name: 'Financial Conglomerates', proxySymbol: 'XLF', aliases: [] },
  { name: 'Electronic Gaming & Multimedia', proxySymbol: 'HERO', aliases: [] },
]

const LOOKUP = new Map()

for (const item of INDUSTRY_UNIVERSE) {
  LOOKUP.set(normalizeIndustryKey(item.name), item)
  for (const alias of item.aliases || []) {
    LOOKUP.set(normalizeIndustryKey(alias), item)
  }
}

export function findIndustryDefinition(value) {
  return LOOKUP.get(normalizeIndustryKey(value)) || null
}
