export const INDUSTRY_ETF_SOURCES = [
  'AMEX:MORT',
  'NASDAQ:AIRR',
  'AMEX:IAI',
  'AMEX:IHF',
  'AMEX:IHE',
  'CBOE:VPN',
  'NASDAQ:INDS',
  'AMEX:REZ',
  'AMEX:COPX',
  'AMEX:FFTY',
  'AMEX:XES',
  'AMEX:BLOK',
  'AMEX:XTL',
  'AMEX:XME',
  'AMEX:GNR',
  'AMEX:BUZZ',
  'AMEX:PBW',
  'NASDAQ:CIBR',
  'AMEX:USO',
  'AMEX:XAR',
  'AMEX:SLX',
  'AMEX:ROBO',
  'AMEX:XSD',
  'AMEX:MOO',
  'AMEX:GXC',
  'NASDAQ:DRIV',
  'CBOE:PAVE',
  'AMEX:GBTC',
  'NASDAQ:WCLD',
  'AMEX:PEJ',
  'AMEX:KRE',
  'AMEX:FXI',
  'AMEX:IPAY',
  'AMEX:XOP',
  'AMEX:XBI',
  'AMEX:KBE',
  'AMEX:XHB',
  'AMEX:XSW',
  'AMEX:BOAT',
  'AMEX:JETS',
  'AMEX:PBJ',
  'AMEX:XTN',
  'AMEX:IBUY',
  'AMEX:XRT',
  'AMEX:XHS',
  'AMEX:XHE',
  'AMEX:KIE',
]

const INDUSTRY_COLORS = [
  '#4db8ff',
  '#00e5a0',
  '#ffaa00',
  '#ff6b9d',
  '#a78bfa',
  '#f59e0b',
  '#6ee7b7',
  '#fca5a5',
  '#93c5fd',
  '#d9f99d',
  '#fb923c',
  '#818cf8',
]

export const INDUSTRY_ETF_UNIVERSE = INDUSTRY_ETF_SOURCES.map((source, index) => {
  const ticker = source.split(':').pop()
  return {
    id: ticker,
    label: ticker,
    ticker,
    source,
    color: INDUSTRY_COLORS[index % INDUSTRY_COLORS.length],
  }
})
